Deep Learning refers to the artificial neural network 

In [1]:
from keras.datasets import mnist
(train_images, train_labels),(test_images,test_labels) = mnist.load_data()

Using TensorFlow backend.


11493376/11490434 [==============================] - 1s 0us/step


In [2]:
# Get the statistics of the taining and testing data
print(train_images.shape)
print(train_labels.shape)

print(test_images.shape)
print(test_labels.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [3]:
from keras import layers
from keras import models
network = models.Sequential()
network.add(layers.Dense(512, activation='relu',input_shape=(28*28,)))
network.add(layers.Dense(10,activation='softmax'))

W0828 06:38:05.793961 139952289064832 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0828 06:38:05.847576 139952289064832 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0828 06:38:05.857577 139952289064832 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [4]:
print(network.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_2 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________
None


In [5]:
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

W0828 06:38:09.586049 139952289064832 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0828 06:38:09.615751 139952289064832 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [0]:
# Reshaping the values
train_images = train_images.reshape((60000,28*28))
test_images = test_images.reshape((10000,28*28))

In [0]:
# Convert the type of float 
train_images = train_images.astype('float32')/255
test_images = test_images.astype('float32')/255

In [8]:
from keras.utils import to_categorical
print(train_labels)
train_labels = to_categorical(train_labels)

[5 0 4 ... 5 6 8]


In [9]:
print(train_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [10]:
network.fit(train_images, train_labels,epochs=5, batch_size=128)

W0828 06:38:19.671321 139952289064832 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0828 06:38:19.727773 139952289064832 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/5
60000/60000 [==============================] - 5s 86us/step - loss: 0.2559 - acc: 0.9261
Epoch 2/5
60000/60000 [==============================] - 5s 75us/step - loss: 0.1040 - acc: 0.9690
Epoch 3/5
60000/60000 [==============================] - 4s 72us/step - loss: 0.0677 - acc: 0.9801
Epoch 4/5
60000/60000 [==============================] - 4s 72us/step - loss: 0.0496 - acc: 0.9855
Epoch 5/5
60000/60000 [==============================] - 4s 73us/step - loss: 0.0374 - acc: 0.9888
